# Generated by Django 3.2 on 2022-08-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('date_of_creation', models.DateField(auto_created=True, auto_now_add=True)),
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('ocid', models.CharField(blank=True, max_length=55)),
                ('x_operation_id', models.CharField(blank=True, max_length=55)),
                ('message', models.JSONField()),
            ],
        ),
    ]
